query:
  subgraph: https://api.studio.thegraph.com/query/53404/thena-bsc-v1/version/latest
  day_data_query: {"operationName": "dayDatas", "variables": {"startTime": 1672790400, "skip": 0}, "query": "query dayDatas($startTime: Int!, $skip: Int!) {\n  dayDatas(skip: $skip, where: {date_gt: $startTime}, orderBy: date, orderDirection: asc) {\n    id\n    date\n    totalVolumeUSD\n    dailyVolumeUSD\n    dailyVolumeETH\n    totalLiquidityUSD\n    totalLiquidityETH\n    __typename\n  }\n}\n"}
  pair_data_query: {"operationName":"pairDayDatas","variables":{"startTime": 1672790400,"pairAddress":"0","skip":0},"query":"query pairDayDatas($startTime: Int!, $pairAddress: Bytes!, $skip: Int!) {\n  pairDayDatas(skip: $skip, orderBy: date, orderDirection: asc, where: {date_gt: $startTime, pairAddress: $pairAddress}) {\n    id\n    date\n    dailyVolumeToken0\n    dailyVolumeToken1\n    dailyVolumeUSD\n    reserveUSD\n    __typename\n  }\n}"}
  id_data_query: {"operationName": "pairs", "variables": {"skip": 0}, "query": "query pairs($skip: Int!) {\n  pairs(skip: $skip) {\n    id\n    __typename\n  }\n}"}
  fusion_subgraph: https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/Hnjf3ipVMCkQze3jmHp8tpSMgPmtPnXBR38iM4ix1cLt
  day_data_fusion_query: {"operationName": "fusionDayDatas", "variables": {"startTime": 1672790400, "skip": 0}, "query": "query fusionDayDatas($startTime: Int!, $skip: Int!) {\n fusionDayDatas(skip: $skip, where: {date_gt: $startTime}, orderBy: date, orderDirection: asc) {\n id\n date\n volumeUSD\n feesUSD\n tvlUSD\n __typename\n }\n}\n"}
  pair_data_fusion_query: {"operationName":"pairDayDatasV3","variables":{"pairAddress":"0","skip":0,"startTime":1681948800},"query":"query pairDayDatasV3($pairAddress: Bytes!, $skip: Int!, $startTime: Int!) {\n  poolDayDatas(skip: $skip, orderBy: date, orderDirection: asc, where: {pool: $pairAddress, date_gt: $startTime}) {\n    id\n    date\n    tvlUSD\n    volumeUSD\n    volumeToken0\n    volumeToken1\n    token0Price\n    token1Price\n    feesUSD\n    __typename\n  }\n}"}
  v1_mint_query: {"operationName": "pairs", "variables": {"skip": 0, "pairAddress": "your_pair_address_here", "startTime": 1704067200}, "query": "query pairs($skip: Int!, $pairAddress: ID!, $startTime: BigInt!) {\n  pairs(where: {id: $pairAddress}) {\n    mints(\n      skip: $skip,\n      where: {timestamp_gt: $startTime, amountUSD_gt: 0}\n      orderBy: timestamp\n      orderDirection: asc\n    ) {\n      transaction {\n        id\n      }\n      timestamp\n      amountUSD\n    }\n  }\n}\n"}
  v1_burn_query: {"operationName": "pairs", "variables": {"skip": 0, "pairAddress": "your_pair_address_here", "startTime": 1704067200}, "query": "query pairs($skip: Int!, $pairAddress: ID!, $startTime: BigInt!) {\n  pairs(where: {id: $pairAddress}) {\n    burns(\n      skip: $skip,\n      where: {timestamp_gt: $startTime, amountUSD_gt: 0}\n      orderBy: timestamp\n      orderDirection: asc\n    ) {\n      transaction {\n        id\n      }\n      timestamp\n      amountUSD\n    }\n  }\n}\n"}
  cl_mint_query: {"operationName": "pools", "variables": {"skip": 0, "poolAddress": "your_pool_address_here", "startTime": 1704067200}, "query": "query pools($skip: Int!, $poolAddress: ID!, $startTime: BigInt!) {\n  pools(where: {id: $poolAddress}) {\n    mints(\n      skip: $skip,\n      where: {timestamp_gt: $startTime, amountUSD_gt: 0}\n      orderBy: timestamp\n      orderDirection: asc\n    ) {\n      transaction {\n        id\n      }\n      timestamp\n      amountUSD\n    }\n  }\n}\n"}
  cl_burn_query: {"operationName": "pools", "variables": {"skip": 0, "poolAddress": "your_pool_address_here", "startTime": 1704067200}, "query": "query pools($skip: Int!, $poolAddress: ID!, $startTime: BigInt!) {\n  pools(where: {id: $poolAddress}) {\n    burns(\n      skip: $skip,\n      where: {timestamp_gt: $startTime, amountUSD_gt: 0}\n      orderBy: timestamp\n      orderDirection: asc\n    ) {\n      transaction {\n        id\n      }\n      timestamp\n      amountUSD\n    }\n  }\n}\n"}
  
web3:
  provider_url: https://rpc.ankr.com/bsc
  provider_urls: ['https://rpc.ankr.com/bsc', 'https://binance.llamarpc.com', 'https://bsc.meowrpc.com', 'https://bsc-dataseed.bnbchain.org']
  id_abi: [{"inputs":[],"name":"pool","outputs":[{"internalType":"contract IAlgebraPool","name":"","type":"address"}],"stateMutability":"view","type":"function"}]


  ve_contract: "0x3A1D0952809F4948d15EBCe8d345962A282C4fCb"
  amm_abi: 
  voter_abi: 
  bribe_abi: 
  gauge_abi: 
  cl_gauges_contract: "0xb065E4F5D71a55a4e4FC2BD871B36E33053cabEB"
  cl_gauges_abi: 
  cl_gauge_abi: 
  cl_token_abi: 
  
gsheets:
  daily_data_sheet_key: 
  pair_data_sheet_key: 
  bribe_data_sheet_key: 
  emissions_data_sheet_key: 
  revenue_data_sheet_key: 
  daily_data_fusion_sheet_key: 
  pair_data_fusion_sheet_key: 
  daily_data_combined_sheet_key: 
  pair_data_combined_sheet_key: 
  fee_data_sheet_key: 
  revenue_data_v2_sheet_key: 
  tvl_data_sheet_key: 
  
api:
  price_api: https://api.thena.fi/api/v1/assets
  fusion_api: https://api.thena.fi/api/v1/fusions
  
files:
  epoch_data: 
  epoch_daily_data: 
  bribe_data: 
  id_data: https://raw.githubusercontent.com/ALMIGHTYABE/Thena-Data-2/main/data/id_data.csv
  daily_data: 
  pair_data: 
  emissions_data: 
  daily_data_fusion: 
  pair_data_fusion: 
  daily_data_combined: 
  pair_data_combined: 
  fee_data: 
  tvl_data: 


